spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id : product-route
          ## lb 负载均衡 默认都到rerenfast
          uri : lb://mall-product
          predicates:
          ## 都带/product
           - Path=/api/product/**
          filters:
          ## 路径重写
          - RewritePath=/api/product/(?<segment>.*),/product/$\{segment}

        - id : product-third-party
          uri : lb://mall-third-party
          predicates:
          ## 都带/product
           - Path=/api/thirdparty/**
          filters:
          ## 路径重写
          - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id : admin-route
          uri : lb://renren-fast
          predicates:
          ##前端项目 都带/api
           - Path=/api/**
          filters:
          ## 路径重写
          - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}

